### ISSUE TITLE
Stalls when using port

### ISSUE THREAD

**Issue by nomasprime** [otahi/infrataster-plugin-firewall#6]
`it { is_expected.to be_reachable }` works as expected but `it { is_expected.to be_reachable.tcp.dest_port(80) }` outputs `via firewall` and a blinking cursor indefinitely.

This is the repo I'm working on - https://github.com/habitullence/ansible-demo. Should be able to reproduce by adding a test to existing spec file.

**Comment by otahi** [comment]
Thank you for your reporting!
Can you describe more details?
- which test code do you use?
- can you ssh to the VM without password or yes/no questions?
- `is_expected.to be_reachable.tcp.dest_port(80).ack(:only)` works?

**Comment by nomasprime** [comment]
No problem, thanks for the plugin.
- I'm using the integration tests
- Yes
- The test fails

It's stalling somewhere in https://github.com/otahi/infrataster-plugin-firewall/blob/master/lib/infrataster/plugin/firewall/capture.rb#L50.

**Comment by nomasprime** [comment]
This seems to be the point of no return https://github.com/otahi/infrataster-plugin-firewall/blob/master/lib/infrataster/plugin/firewall/capture.rb#L76.

**Comment by otahi** [comment]
@habitullence I am very sorry about my late response.
I have found the test case can be passed with net-ssh 3.0.2. But the test fails with net-ssh 3.1.1.

I will dive into net-ssh.

**Comment by otahi** [comment]
@h

**Comment by otahi** [comment]
@habitullence Can you try to check #7?
If it is OK for you, I will merge and release this modification.
Thank you.
